name: flutter_myinsta
description: Flutter_myinsta.

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0

flutter:


  uses-material-design: true


  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  fonts:
   - family: Billabong
     fonts:
      - asset: assets/fonts/Billabong.ttf

   - family: Nottingsam_Demo
     fonts:
      - asset: assets/fonts/Nottingsam_Demo.ttf
