name: flutter_myinsta
description: Flutter_myinsta.

version: 1.0.0+1

environment:
  sdk: ">=2.07.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  image_picker: ^0.6.6+5
  fluttertoast: 7.1.1
  flutter_icons: 1.1.0
  cached_network_image: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0

flutter:


  uses-material-design: true


  assets:
     - assets/images/
  #   - images/a_dot_ham.jpeg


  fonts:
   - family: Billabong
     fonts:
      - asset: assets/fonts/Billabong.ttf

   - family: Nottingsam_Demo
     fonts:
      - asset: assets/fonts/Nottingsam_Demo.ttf
